name = "BDM Sticky Add to Cart Bar"
client_id = "YOUR_SHOPIFY_APP_API_KEY"

application_url = "https://YOUR_DEPLOYED_URL"
embedded = true

[auth]
redirect_urls = [
  "https://YOUR_DEPLOYED_URL/auth/callback",
  "https://YOUR_DEPLOYED_URL/auth/shopify/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
